// src/components/WorkExperience/WorkExperience.tsx
import {loadWorkExperience} from 'src/resources/work-experience';
import {WorkExperienceDto} from 'src/types/dto';
import React, {useEffect, useState} from "react";
import {Grid, Title} from '@mantine/core';
import {WorkExperienceItem} from './WorkExperience.item';


export const WorkExperience = () => {
  const [workExperience, setWorkExperience] = useState<WorkExperienceDto[]>([]);
  const [tags, setTags] = useState<string[]>([]);

  useEffect(() => {
    setWorkExperience(loadWorkExperience());

    workExperience.forEach(({technologiesTags}) => {
      setTags([...tags, ...technologiesTags]);
    });
  });

  return (
    <Grid>
      <Grid.Col xs={12} p={0}>
        <Title order={2}>Опыт работы</Title>
      </Grid.Col>
      {workExperience.map((item) => (
        <Grid.Col xs={12} xl={3} lg={4} sm={2} md={4} p={0}>
          <WorkExperienceItem {...item} />
        </Grid.Col>
      ))}
    </Grid>
  );
}

// src/app/components/work-experience/work-experience.component.ts
import {Component, OnInit} from '@angular/core';
import {loadWorkExperience} from 'src/resources/work-experience';
import {WorkExperienceDto} from 'src/types/dto';


@Component({
  selector: 'app-work-experience',
  templateUrl: './work-experience.component.html',
  styleUrls: ['./work-experience.component.scss']
})
export class WorkExperienceComponent implements OnInit {
  workExperience: WorkExperienceDto[] = [];
  tags: string[] = [];

  ngOnInit(): void {
    loadWorkExperience().then((workExperience) => {
      this.workExperience = workExperience;

      workExperience.map(({technologiesTags}) => {
        this.tags = [...this.tags, ...technologiesTags];
      });
    });
  }
}

<div class="row">
  <div class="col-12"><h2>Опыт работы</h2></div>
  <div
    class="card col-md-6 col-sm-12 col-lg-4 col-xxl-3 col-12 mb-4"
    *ngFor="let item of workExperience"
  >
    <div class="card-body">
      <h5 class="card-title">
        {{item.companyName}}
      </h5>
      <p>
        <span class="badge bg-dark">
          <app-work-interval [dateBegin]="item.dateBegin" [dateEnd]="item.dateEnd"></app-work-interval>
        </span>
      </p>

      <p *ngIf="item.workPosition" class="card-subtitle">{{item.workPosition}}</p>
      <p *ngIf="item.teamName" class="card-subtitle">{{item.teamName}}</p>
      <div class="card-text">{{item.description}}</div>
      <p>
        <a
          *ngIf="item.companySite"
          target="_blank"
          [href]="item.companySite"
        >
          {{item.companySiteName || item.companySite}}
        </a>
      </p>
    </div>
    <div class="card-footer">
      <div *ngIf="item.technologiesTags.length > 0">
        <span
          class="badge bg-secondary me-1"
          *ngFor="let tag of item.technologiesTags"
        >
          {{tag}}
        </span>
      </div>
    </div>
  </div>
  <div class="col-12 overflow-hidden">
    <app-cloud-tags *ngIf="tags" [cloudTags]="tags"></app-cloud-tags>
  </div>
</div>
