// src/components/work-experience/work-experience.component.tsx
import {isEmpty} from 'lodash';
import {loadWorkExperience} from 'src/resources/work-experience';
import {WorkExperienceDto} from 'src/types/dto';
import {useEffect, useState} from "react";


export const WorkExperienceComponent = () => {
  const [workExperience, setWorkExperience] = useState<WorkExperienceDto[]>([]);
  const [tags, setTags] = useState<string[]>([]);

  const isMobile = () => (window.screen.width < 768)

  const isShowCloudTags = () => {
    return !isEmpty(tags) && !isMobile();
  }

  useEffect(() => {
    setWorkExperience(loadWorkExperience());

    workExperience.forEach(({technologiesTags}) => {
      setTags([...tags, ...technologiesTags]);
    });
  });

  return (
    <div className="row">
      <div className="col-12"><h2>Опыт работы</h2></div>
      {workExperience.map((item) => (
        <div className="card col-md-6 col-sm-12 col-lg-4 col-xxl-3 col-12 mb-4">
          <div className="card-body">
            <h5 className="card-title">
              {item.companyName}
            </h5>
            <p>
              <span className="badge bg-dark">
                {/*<app-work-interval [dateBegin]="item.dateBegin" [dateEnd]="item.dateEnd"></app-work-interval>*/}
              </span>
            </p>

            {item.workPosition && (<p className="card-subtitle">{item.workPosition}</p>)}
            {item.teamName && (<p className="card-subtitle">{item.teamName}</p>)}
            <div className="card-text">{item.description}</div>
            <p>
              {item.companySite && (
                <a target="_blank" href={item.companySite}>
                  {item.companySiteName || item.companySite}
                </a>
              )}
            </p>
          </div>

          <div className="card-footer">
            {(item.technologiesTags.length > 0) ? (
              <div>
                {item.technologiesTags.map((tag) => (
                  <span className="badge bg-secondary me-1">{tag}</span>
                ))}
              </div>
            ) : null}
          </div>
        </div>
      ))}
      {/*<div className="col-12 overflow-hidden">*/}
      {/*  <app-cloud-tags *ngIf="isShowCloudTags" [cloudTags]="tags"></app-cloud-tags>*/}
      {/*</div>*/}
    </div>
  );
}

// fe-angular/src/app/components/work-experience/work-experience.component.ts
import {Component, OnInit} from '@angular/core';
import dataWorkExperience from './work-experience.json';

interface WorkExperience {
  dateBegin: string,
  dateEnd: string,
  companyName: string,
  companySite?: string,
  workPosition: string,
  teamName?: string,
  technologiesTags: string[],
  description: string
}

@Component({
  selector: 'app-work-experience',
  templateUrl: './work-experience.component.html',
  styleUrls: ['./work-experience.component.scss']
})
export class WorkExperienceComponent implements OnInit {
  workExperience: WorkExperience[] = [];

  constructor() {
    this.workExperience = dataWorkExperience;
  }

  ngOnInit(): void {
  }

}

<div class="row">
  <div class="col-12"><h2>Опыт работы</h2></div>
  <div
    class="card col-md-4 col-sm-6 col-12"
    *ngFor="let item of workExperience"
  >
    <div class="card-body">
      <h5 class="card-title">
        {{item.companyName}}
        <a *ngIf="item.companySite" [href]="item.companySite">{{item.companySite}}</a>
      </h5>
      <p *ngIf="item.workPosition" class="card-subtitle">{{item.workPosition}}</p>
      <p *ngIf="item.teamName" class="card-subtitle">{{item.teamName}}</p>
      <div class="card-text">{{item.description}}</div>

    </div>
    <div class="card-footer">
      <div *ngIf="item.technologiesTags.length > 0">
        <span
          class="badge bg-secondary me-1"
          *ngFor="let tag of item.technologiesTags"
        >
          {{tag}}
        </span>
      </div>
    </div>
  </div>
</div>
