// src/components/header/header.component.tsx
import {faArrowTrendUp, faArrowTrendDown} from '@fortawesome/free-solid-svg-icons';

export const HeaderComponent = () => {
  const icons = {
    faArrowTrendUp,
    faArrowTrendDown
  }

  return (
    <div className="my-3">
      <h1 className="text-center">Ковалёв Тарас Викторович (taraswww777)</h1>
      <p className="text-center">
        Увеличение
        {/*<fa-icon [icon]="icons.faArrowTrendUp" style="font-size: 1rem; display: inline-block; max-height: 1rem"/>*/}
        прибыли и сокращение
        {/*<fa-icon [icon]="icons.faArrowTrendDown" style="font-size: 1rem; display: inline-block; max-height: 1rem"/></fa-icon>*/}
        издержек
      </p>
    </div>
  );
}

// src/components/header/header.component.ts
import { Component } from '@angular/core';
import {faArrowTrendUp, faArrowTrendDown} from '@fortawesome/free-solid-svg-icons';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent {
  public icons = {
    faArrowTrendUp,
    faArrowTrendDown
  }
}

<div class="my-3">
  <h1 class="text-center">Ковалёв Тарас Викторович (taraswww777)</h1>
  <p class="text-center">
    Увеличение
    <fa-icon [icon]="icons.faArrowTrendUp" style="font-size: 1rem; display: inline-block; max-height: 1rem"></fa-icon>
    прибыли и сокращение
    <fa-icon [icon]="icons.faArrowTrendDown" style="font-size: 1rem; display: inline-block; max-height: 1rem"></fa-icon>
    издержек
  </p>
</div>
